../target/debug/spark-submitter \
	--path /home/xyji/spark/bin/spark-submit \
	--master k8s://https://10.2.7.200:6443 \
	--image xinyouji/pyspark-image:latest \
	--planner fair \
	--scheduler-name spark-sched \
	--pvc-claim-name nfs-pvc-spark \
	--tags storage \
	--meta wc \
	--progs "local:///opt/spark/examples/src/main/python/wordcount.py /mnt/input.txt" \
	--tags storage \
	--meta wc \
	--progs "local:///opt/spark/examples/src/main/python/wordcount.py /mnt/input.txt" \
	--tags storage \
	--meta wc \
	--progs "local:///opt/spark/examples/src/main/python/wordcount.py /mnt/input.txt" \
	--tags storage \
	--meta sort \
	--progs "local:///mnt/sort.py /mnt/input.txt" \
	--tags storage \
	--meta sort \
	--progs "local:///mnt/sort.py /mnt/input.txt" \
	--tags compute \
	--meta pi \
	--progs "local:///opt/spark/examples/src/main/python/pi.py 500" \
	--tags compute \
	--meta svm \
	--progs "local:///opt/spark/examples/src/main/python/mllib/svm_with_sgd_example.py 800" \
